// all-lstm.js - LSTM Data Loader\n// Identical to all-ml.js but fetches data/all-lstm.txt\nasync function fetchAndParseAllLSTMData() {\n  console.log('All-LSTM: Fetching data/all-lstm.txt...');\n  \n  try {\n    const response = await fetch('data/all-lstm.txt');\n    if (!response.ok) throw new Error(`Fetch failed: ${response.status}`);\n    \n    const text = await response.text();\n    const lines = text.split('\\n');\n    \n    let dataALines = [];\n    let dataBLines = [];\n    let metricsText = '';\n    let inSection = '';\n    \n    for (let line of lines) {\n      line = line.trim();\n      if (line.startsWith('#') || !line) continue;\n      \n      if (line.includes('Data-A') || line.includes('LSTM')) {\n        inSection = 'A';\n        continue;\n      }\n      if (line.includes('Data-B') || line.includes('Actual')) {\n        inSection = 'B';\n        continue;\n      }\n      if (line.includes('Metric')) {\n        inSection = 'metrics';\n        continue;\n      }\n      \n      if (inSection === 'A' && !line.startsWith('id') && line.match(/^\\d/)) dataALines.push(line);\n      else if (inSection === 'B' && !line.startsWith('id') && line.match(/^\\d/)) dataBLines.push(line);\n      else if (inSection === 'metrics') metricsText += line + '\\n';\n    }\n    \n    // Parse predict/actual arrays (wind/solar min avg max)\n    const predict_wind_avg = dataALines.map(line => parseFloat(line.split(',')[3]));\n    const actual_wind_avg = dataBLines.map(line => parseFloat(line.split(',')[3]));\n    \n    // Update globals for charts\n    window.predict_wind_avg = predict_wind_avg;\n    window.actual_wind_avg = actual_wind_avg;\n    \n    // Update metrics\n    const maeMatch = metricsText.match(/MAE.*?([\\d.-]+)/i);\n    document.getElementById('mae-val') ? document.getElementById('mae-val').textContent = maeMatch ? parseFloat(maeMatch[1]).toFixed(3) : 'N/A' : null;\n    \n    console.log('✅ LSTM data loaded:', predict_wind_avg.length, 'days');\n    updateChartsWithData();\n    \n  } catch (error) {\n    console.error('LSTM Load ERROR:', error);\n  }\n}\n\n// Auto-load on DOM ready\nif (document.readyState === 'loading') {\n  document.addEventListener('DOMContentLoaded', () => setTimeout(fetchAndParseAllLSTMData, 100));\n} else {\n  setTimeout(fetchAndParseAllLSTMData, 100);\n}\n"
</xai:function_call.





<xai:function_call name="edit_file">
<parameter name="path">TODO.md
